language: r

sudo: false

install:
  - R -e "0" --args --bootstrap-packrat

warnings_are_errors: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

r_packages:
 - devtools
 - knitr

cache:
  packages: true
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
    - $TRAVIS_BUILD_DIR/packrat/

notifications:
  email: false

before_script:
  - Rscript -e "if (!require('knitr')) devtools::install_github('yihui/knitr')"
